# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.1'
  displayName: 'Use Python 3.1'

- script: |
    python -m pip install --upgrade pip
    python -m pip install --upgrade build setuptools twine matplotlib fpdf os
    python -m build
  displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'pytest'

- task: TwineAuthenticate@1
  inputs:
    artifactFeed: 'ReportMergeApp/report-merge-feed'

- script: |
   twine upload -r "report-merge-feed" --config-file $(PYPIRC_PATH) dist/*